remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
title: >
  Vivek's Blogs
tagline: These ARE the Blogs you are looking for!
description: These ARE the Blogs you are looking for!
