remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: >
  Vivek's Blogs
tagline: There ARE the Blogs you are looking for!
description: There ARE the Blogs you are looking for!
